EXEC sp_rename 'silver.dataco_supply_chain.Type', 'payment_type', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Days for shipping (real)', 'actual_shipping_days', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Days for shipment (scheduled)', 'scheduled_delivery_days', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Benefit per order', 'earning_per_order', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Sales per customer', 'total_sale_per_customer', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Benefit per order', 'earning_per_order', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Delivery Status', 'order_delivery_status', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Late_delivery_risk', 'order_late_delivery_risk', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Category Id', 'product_category_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Category Name', 'product_category_name', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer City', 'customer_city', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Country', 'customer_country', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Email', 'customer_email', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Fname', 'customer_first_name', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Id', 'customer_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Lname', 'customer_last_name', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Password', 'customer_password', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Segment', 'types_of_customers', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer State', 'customer_state', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Street', 'customer_street', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Customer Zipcode', 'customer_zipcode', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Department Id', 'store_department_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Department Name', 'store_department_name', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Latitude', 'store_location_latitude', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Longitude', 'store_location_longitude', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.order_continent_delivered', 'order_continent', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.order_subregion_delivered', 'order_subregion', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order City', 'order_city', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Country', 'order_country', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Customer Id', 'order_customer_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.order date (DateOrders)', 'order_date', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Id', 'order_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.product_barcode_id', 'order_item_product_barcode_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Discount', 'order_item_discount', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Discount Rate   ', 'order_item_discount_percentage', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Id', 'order_item_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Product Price', 'order_item_unit_price', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Profit Ratio', 'order_item_profit_ratio', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Quantity', 'order_item_quantity', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Sales', 'order_item_gross_total', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Item Total ', 'order_item_net_total', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Profit Per Order', 'order_profit_per_order', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order State', 'order_state', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Status', 'order_status', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Order Zipcode', 'order_zipcode', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Product Card Id', 'product_barcode_id', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Product Category Id', 'product_category_id_duplicate', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Product Description', 'product_description', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Product Name', 'product_name', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Product Price', 'product_price', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Product Status', 'product_status', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Shipping date (DateOrders)', 'shipping_date', 'COLUMN';
EXEC sp_rename 'silver.dataco_supply_chain.Shipping Mode', 'shipping_mode', 'COLUMN';
